 CLS
 COLOR 1, 0'dark blue
 PRINT "1 ";
 COLOR 2, 0'light green
 PRINT "2 ";
 COLOR 3, 0'light blue
 PRINT "3 ";
 COLOR 4, 0'red
 PRINT "4 ";
 COLOR 5, 0'purple
 PRINT "5 ";
 COLOR 6, 0'brown
 PRINT "6 ";
 COLOR 7, 0'white
 PRINT "7 ";
 COLOR 8, 0'grey
 PRINT "8 ";
 COLOR 9, 0'bright blue
 PRINT "9 ";
 COLOR 10, 0'   bright green
 PRINT "10 ";
 COLOR 11, 0 '  bright light blue
 PRINT "11 ";
 COLOR 12, 0'   bright orange
 PRINT "12 ";
 COLOR 13, 0'   bright pink
 PRINT "13 ";
 COLOR 14, 0'   bright yellow
 PRINT "14 ";
 COLOR 15, 0 '  bright white
 PRINT "15 ";
 COLOR 16, 0
 PRINT "16 ";
 COLOR 17, 0  ' flashing dark blue
 PRINT "17 ";
 COLOR 18, 0 '  flashing green
 PRINT "18 ";
 COLOR 19, 0 '  flashing light blue
 PRINT "19 ";
 COLOR 20, 0 '  flashing red
 PRINT "20 ";
 COLOR 21, 0 '  flashing purple
 PRINT "21 ";
 COLOR 22, 0 '  flashing brown
 PRINT "22 ";
 COLOR 23, 0 '  flashing light blue
 PRINT "23 ";
 COLOR 24, 0 '  flashing grey
 PRINT "24 ";
 COLOR 25, 0 '  flashing light blue
 PRINT "25 ";
 COLOR 26, 0 '  flashing bright green
 PRINT "26 ";
 COLOR 27, 0 '  flashing bright blue
 PRINT "27 ";
 COLOR 28, 0 '  flashing bright orange
 PRINT "28 ";
 COLOR 29, 0 '  flashing pink
 PRINT "29 ";
 COLOR 30, 0 '  flashing bright yellow
 PRINT "30 ";
 COLOR 31, 0 '  flashing bright white
 PRINT "31 ";

