'Special keys
'F1    = CHR$(0) + ";"
'F2    = CHR$(0) + "<"
'F3    = CHR$(0) + "="
'F4    = CHR$(0) + ">"
'F5    = CHR$(0) + "?"
'F6    = CHR$(0) + "@"
'F7    = CHR$(0) + "A"
'F8    = CHR$(0) + "B"
'F9    = CHR$(0) + "C"
'F10   = CHR$(0) + "D"
'F11   = CHR$(0) + "…"
'F12   = CHR$(0) + "†"
'UP    = CHR$(0) + "H"
'DOWN  = CHR$(0) + "P"
'LEFT  = CHR$(0) + "K"
'RIGHT = CHR$(0) + "M"















                                    







