CLS
SCREEN 1
CIRCLE (150, 60), 8                     'head
LINE (150, 70 - 2)-(145, 70 + 30)       'body
LINE -(115, 140)                        'leg
LINE -(120, 145)                        'feet
LINE (145, 100)-(170, 120)              'thigh
LINE -(170, 140)                        'leg
LINE -(175, 140)                        'feet
LINE (149, 75)-(140, 90)                'uarm
LINE -(164, 95)                         'larm
LINE (149, 75)-(155, 85)                'uarm
LINE -(167, 88)                         'larm












