CLS
SCREEN 1
CIRCLE (150, 50), 9           'head
LINE (150, 58)-(150, 100)     'body
LINE (150, 70)-(140, 80)      'uarm
LINE -(130, 60)               'larm
LINE (150, 70)-(170, 80)      'uarm
LINE -(160, 90)               'larm
CIRCLE (150, 118), 20         'wheel

LINE (130, 118)-(170, 118)    'spook
LINE (150, 102)-(150, 134)
LINE (136, 108)-(165, 128)
LINE (165, 108)-(135, 128)











