CLS
SCREEN 1
LINE (140, 50)-(155, 65), , B
LINE (147, 65)-(142, 70)        'body
LINE (146, 65)-(151, 70)        'body
LINE -(151, 100)                'body
LINE (142, 70)-(142, 100)       'body
LINE -(146, 115)                'body
LINE (151, 100)-(146, 115)      'body

LINE (146, 115)-(134, 140)      'leg
LINE -(139, 140)                'feet

LINE (146, 115)-(157, 140)      'leg
LINE -(162, 140)                'feet

LINE (146, 75)-(138, 90)        'arm
LINE -(160, 80)                 'arm
LINE (142, 75)-(135, 85)        'arm/
LINE -(142, 82)                 'arm/
LINE (151, 80)-(160, 75)        'arm/











